name: lock-pacman
type: shell
commands:
  - lpkg --lock
modules:
  - name: ensure-initd-executable
    type: shell
    commands:
      - chmod +x /usr/share/init.d/010-fsguard.sh

  - name: blackbox-rescue
    type: shell
    commands:
      - echo "\nActions=rescue;\n[Desktop Action rescue]\nName=Rescue Mode\nExec=blackbox-terminal -c /bin/bash\nIcon=com.raggesilver.BlackBox" >> /usr/share/applications/com.raggesilver.BlackBox.desktop

  - name: sysconf-setup
    type: shell
    commands:
      - rsync -a /etc/ /sysconf/
