name: Planifolia Desktop
id: desktop

stages:
- id: build
  base: ghcr.io/planifolia-images/core:dev
  singlelayer: false
  labels:
    maintainer: nisel11

  modules:
  - name: packages-modules
    type: includes
    includes:
      - modules/01-gnome.yml
      - modules/02-gnome-essentials.yml
      - modules/03-gnome-software-vso-plugin.yml
      - modules/04-desktop-entries.yml
      - modules/05-configure.yml

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/lib/planifolia/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard
          - rm -f ./minisign.pub ./minisign.key

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/cache/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
